import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";

import { readPdfResources, readPdfResourceLicenses } from "./scripts/pdf-resources.mjs";

const banner = `/*
${fs.readFileSync("LICENSE", "utf8")}
Bundled PDF.js license:
${fs.readFileSync("THIRD-PARTY-LICENSES.txt", "utf8")}
Bundled font and decoder licenses:
${readPdfResourceLicenses().replaceAll("*/", "* /")}
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// package.json owns the plugin version. Preserve earlier compatibility entries.
const packageInfo = JSON.parse(fs.readFileSync("package.json", "utf8"));
const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
const versions = JSON.parse(fs.readFileSync("versions.json", "utf8"));
manifest.version = packageInfo.version;
versions[packageInfo.version] = manifest.minAppVersion;
for (const [path, data] of [["manifest.json", manifest], ["versions.json", versions]]) {
	const contents = JSON.stringify(data, null, 2) + "\n";
	if (fs.readFileSync(path, "utf8") !== contents) fs.writeFileSync(path, contents);
}

// Embeds the worker in main.js and concatenates the pdf.js viewer CSS
// (text layer styles) with our own styles into Obsidian's expected styles.css.
const assetPlugin = {
	name: "paper-reader-assets",
	setup(build) {
		build.onEnd(() => {
			const viewerCss = fs.readFileSync(
				"node_modules/pdfjs-dist/legacy/web/pdf_viewer.css",
				"utf8"
			);
			const customCss = fs.existsSync("src/styles.css")
				? fs.readFileSync("src/styles.css", "utf8")
				: "";
			fs.writeFileSync("styles.css", viewerCss + "\n" + customCss);
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	define: { __PDF_RESOURCES__: JSON.stringify(readPdfResources()), __PDF_WORKER_SOURCE__: JSON.stringify(fs.readFileSync("node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs", "utf8")) },
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		"node:*",
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: "main.js",
	plugins: [assetPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
